import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleDriver;
import oracle.jdbc.OracleTypes;
import oracle.jdbc.pool.OracleDataSource;
//import sun.security.util.Password;
public class Login extends javax.swing.JFrame {
public Connection con;
String username,password1;
Map <String,String> credntials;  
    /**
     * Creates new form Login
     */
    public Login() {
       
        credntials=new HashMap<String, String>();
        credntials.clear();
            credntials.put("VShah","Shah24" );
            credntials.put("Rahul24","rahul2424" );
        password1="";
        username="";
         initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Loginid = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        LoginDB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Form");
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setName("Login_Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jLabel5.setBackground(new java.awt.Color(102, 102, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("                       STUDENT REGISTRATION SYSTEM");
        jLabel5.setToolTipText("cxcx");
        jLabel5.setFocusTraversalPolicyProvider(true);
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 20, 760, 40);

        jPanel3.setBackground(new java.awt.Color(102, 102, 0));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login ID");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(29, 58, 52, 15);
        jPanel3.add(Loginid);
        Loginid.setBounds(122, 46, 150, 30);
        jPanel3.add(password);
        password.setBounds(122, 113, 145, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(29, 114, 60, 17);

        LoginDB.setText("Login");
        LoginDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginDBActionPerformed(evt);
            }
        });
        jPanel3.add(LoginDB);
        LoginDB.setBounds(73, 178, 106, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(80, 140, 280, 240);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mitesh\\Desktop\\Image.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 760, 470);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(2228, 11, 173, 287);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(430, 120, 100, 100);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(900, 220, 370, 100);

        pack();
    }// </editor-fold>                        

    private void LoginDBActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
   try
        {
            if(Loginid.getText().toString().equals(""))
            {
                JOptionPane.showMessageDialog(null,"please enter the login id");
            }
            else if(password.getText().toString().equals(""))
            {
              JOptionPane.showMessageDialog(null,"please enter the password");

            }
            else
            {
          username=Loginid.getText().trim().toLowerCase().toString();
          password1=password.getText().trim().toLowerCase().toString();
         
          Class.forName("oracle.jdbc.driver.OracleDriver");
          con= DriverManager.getConnection("jdbc:oracle:thin:@15R:1522:XE",username,password1);
          STudentsSystem sy=new STudentsSystem(con,username);
       //  JOptionPane.showMessageDialog(null,"Login Successsul");

          sy.show();  
          
          
            }
            
            
            
            
          
        }
        catch(Exception ed)
        {
         JOptionPane.showMessageDialog(null,"invalid username/password; logon denied");
        }
        
        
        
        
        
        
    }                                       

    
//    private void showtable(String procname,String Table_name)
//    {
//        try{
//           System.out.println(procname);
//        CallableStatement cb=con.prepareCall(procname);
//        cb.setString(1,Table_name);
//      cb.registerOutParameter(2, OracleTypes.CURSOR);
//      cb.executeUpdate();
//      ResultSet rs=(ResultSet)cb.getObject(2);
//      ResultSetMetaData rsmd=rs.getMetaData();
//      int col=rsmd.getColumnCount();
//      String columns[]=new String[col];
//      for(int i=0;i<col;i++)
//      {
//          columns[i]=rsmd.getColumnName(i+1);
//      }
//       
//       ConvertToJtable ct=new ConvertToJtable();
//               DefaultTableModel model=(DefaultTableModel)jTable1.getModel();    
//
//       model.setRowCount(0);
//         jTable1.setModel(model);
//         model=ct.ConverttoTable((DefaultTableModel)jTable1.getModel(), columns, rs);
//      
//       jTable1.setModel(model);
//        }
//        catch(Exception ex)
//        {
//            ex.printStackTrace();
//        }
//        
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton LoginDB;
    private javax.swing.JTextField Loginid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField password;
    // End of variables declaration                   
}
