/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
//package studentregistrationsystem;

import java.awt.Color;
import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleDriver;
import oracle.jdbc.OracleTypes;
import oracle.jdbc.pool.OracleDataSource;
//import sun.security.util.Password;
/**
 *
 * @author Mitesh
 */
public class STudentsSystem extends javax.swing.JFrame {

    
    private static String Username="";
    private static String password="";
   public static Connection con;
    private DefaultTableModel model;
    /**
     * Creates new form STudentsSystem
     */
    public STudentsSystem(Connection con1,String User) {
        
       con=con1;
        Username=User;
        initComponents();
        jPanel1.setVisible(true);
        viewpanel.setVisible(true);
          viewpanel.setVisible(true);
        SearchPane.setVisible(false);
        UpdatePanel.setVisible(false);
        jLabel10.setText("View Tables");
        //jPanel3.setVisible(false);
       //jLabel13.setText("Welcome  "+ Username);   
      
       jTable2.setVisible(false);
       jLabel16.setText("                                                               WELCOME - "+User.toUpperCase() + "    TO STUDENT REGISTRATION SYSTEM");

       DefaultTableModel model;
 showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.students","B#",jTable2);   
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel1 = new javax.swing.JPanel();
        SearchDetails = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        SearchPane = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        dept_code = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Errorclass2 = new javax.swing.JLabel();
        SearchClass2 = new javax.swing.JButton();
        Classespane2 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        course1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Student_id = new javax.swing.JTextField();
        SearchClass = new javax.swing.JButton();
        Errorclass = new javax.swing.JLabel();
        Classespane = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        Classespane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        class_id = new javax.swing.JTextField();
        SearchClass1 = new javax.swing.JButton();
        Errorclass1 = new javax.swing.JLabel();
        viewpanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Students = new javax.swing.JButton();
        Classes = new javax.swing.JButton();
        Courses = new javax.swing.JButton();
        Grades = new javax.swing.JButton();
        Prereq = new javax.swing.JButton();
        credits = new javax.swing.JButton();
        logss = new javax.swing.JButton();
        enroll = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        UpdatePanel = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        EnrollStudents1 = new javax.swing.JPanel();
        ErrorEnroll2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EnrollmentsCid1 = new javax.swing.JTextField();
        EnrollmentsSid2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ErrorEnroll3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        EnrollStudents = new javax.swing.JPanel();
        ErrorEnroll = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EnrollmentsCid = new javax.swing.JTextField();
        EnrollmentsSid1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        EnrollStudents2 = new javax.swing.JPanel();
        ErrorEnroll4 = new javax.swing.JLabel();
        EnrollmentsSid3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ErrorEnroll5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Registration System");
        setBackground(new java.awt.Color(140, 49, 0));
        setMinimumSize(new java.awt.Dimension(1179, 600));
        setName("Student Registration System"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        SearchDetails.setBackground(new java.awt.Color(51, 51, 0));
        SearchDetails.setForeground(new java.awt.Color(255, 255, 255));
        SearchDetails.setText("Search details");
        SearchDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(SearchDetails);
        SearchDetails.setBounds(10, 320, 120, 60);

        jButton2.setBackground(new java.awt.Color(51, 51, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View Details");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 110, 120, 50);

        jButton1.setBackground(new java.awt.Color(51, 51, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update details");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 220, 120, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 140, 600);

        SearchPane.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(51, 51, 0));
        jPanel10.setLayout(null);

        dept_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dept_codeActionPerformed(evt);
            }
        });
        jPanel10.add(dept_code);
        dept_code.setBounds(230, 30, 161, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dept code");
        jPanel10.add(jLabel4);
        jLabel4.setBounds(130, 30, 63, 15);
        jPanel10.add(Errorclass2);
        Errorclass2.setBounds(140, 100, 495, 25);

        SearchClass2.setText("Search Courses");
        SearchClass2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchClass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchClass2ActionPerformed(evt);
            }
        });
        jPanel10.add(SearchClass2);
        SearchClass2.setBounds(340, 80, 140, 30);

        Classespane2.setOpaque(false);

        jTable7.setAutoCreateRowSorter(true);
        jTable7.setBackground(new java.awt.Color(204, 204, 204));
        jTable7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable7.setGridColor(new java.awt.Color(0, 0, 0));
        jTable7.setOpaque(false);
        Classespane2.setViewportView(jTable7);

        jPanel10.add(Classespane2);
        Classespane2.setBounds(180, 140, 450, 190);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Course#");
        jPanel10.add(jLabel5);
        jLabel5.setBounds(430, 30, 51, 15);

        course1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course1ActionPerformed(evt);
            }
        });
        jPanel10.add(course1);
        course1.setBounds(540, 30, 161, 30);

        SearchPane.addTab("Search Courses that requires this courses as prerequisite", jPanel10);

        jPanel5.setBackground(new java.awt.Color(51, 51, 0));
        jPanel5.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 0));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student ID");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(119, 14, 69, 15);

        Student_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_idActionPerformed(evt);
            }
        });
        jPanel2.add(Student_id);
        Student_id.setBounds(217, 12, 161, 30);

        SearchClass.setText("Search Class");
        SearchClass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchClassActionPerformed(evt);
            }
        });
        jPanel2.add(SearchClass);
        SearchClass.setBounds(414, 11, 154, 23);
        jPanel2.add(Errorclass);
        Errorclass.setBounds(136, 48, 495, 25);

        jPanel5.add(jPanel2);
        jPanel2.setBounds(30, 23, 710, 70);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        Classespane.setViewportView(jTable1);

        jPanel5.add(Classespane);
        Classespane.setBounds(20, 100, 700, 210);

        SearchPane.addTab("Search classes taken by given Student", jPanel5);

        jPanel6.setBackground(new java.awt.Color(51, 51, 0));
        jPanel6.setLayout(null);

        jTable3.setBackground(new java.awt.Color(204, 204, 204));
        jTable3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(0, 0, 0));
        Classespane1.setViewportView(jTable3);

        jPanel6.add(Classespane1);
        Classespane1.setBounds(20, 90, 680, 240);

        jPanel3.setBackground(new java.awt.Color(119, 59, 30));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Class ID");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(119, 14, 48, 15);

        class_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_idActionPerformed(evt);
            }
        });
        jPanel3.add(class_id);
        class_id.setBounds(196, 12, 161, 30);

        SearchClass1.setText("Search Students");
        SearchClass1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchClass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchClass1ActionPerformed(evt);
            }
        });
        jPanel3.add(SearchClass1);
        SearchClass1.setBounds(400, 10, 154, 23);
        jPanel3.add(Errorclass1);
        Errorclass1.setBounds(136, 48, 495, 25);

        jPanel6.add(jPanel3);
        jPanel3.setBounds(31, 21, 710, 40);

        SearchPane.addTab("Search Students enrolled in a given class", jPanel6);

        SearchPane.setBounds(50, 20, 890, 410);
        jLayeredPane3.add(SearchPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        viewpanel.setBackground(new java.awt.Color(51, 51, 0));
        viewpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        viewpanel.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(51, 51, 0));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.setLayout(null);

        Students.setText("Students");
        Students.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsActionPerformed(evt);
            }
        });
        jPanel4.add(Students);
        Students.setBounds(30, 20, 90, 23);

        Classes.setText("Classes");
        Classes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Classes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassesActionPerformed(evt);
            }
        });
        jPanel4.add(Classes);
        Classes.setBounds(130, 20, 80, 23);

        Courses.setText("Courses");
        Courses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesActionPerformed(evt);
            }
        });
        jPanel4.add(Courses);
        Courses.setBounds(360, 20, 90, 23);

        Grades.setText("Grades");
        Grades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Grades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradesActionPerformed(evt);
            }
        });
        jPanel4.add(Grades);
        Grades.setBounds(560, 20, 90, 23);

        Prereq.setText("Prereuisites");
        Prereq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Prereq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrereqActionPerformed(evt);
            }
        });
        jPanel4.add(Prereq);
        Prereq.setBounds(790, 20, 110, 23);

        credits.setText("Course_Credits");
        credits.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsActionPerformed(evt);
            }
        });
        jPanel4.add(credits);
        credits.setBounds(220, 20, 130, 23);

        logss.setText("Logs");
        logss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logssActionPerformed(evt);
            }
        });
        jPanel4.add(logss);
        logss.setBounds(460, 20, 80, 23);

        enroll.setText("Enrollments");
        enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollActionPerformed(evt);
            }
        });
        jPanel4.add(enroll);
        enroll.setBounds(660, 20, 120, 23);

        viewpanel.add(jPanel4);
        jPanel4.setBounds(0, 0, 930, 70);

        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setDoubleBuffered(true);
        jTable2.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTable2);

        viewpanel.add(jScrollPane2);
        jScrollPane2.setBounds(70, 120, 770, 250);

        viewpanel.setBounds(60, 0, 930, 430);
        jLayeredPane3.add(viewpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        UpdatePanel.setBackground(new java.awt.Color(255, 255, 255));
        UpdatePanel.setPreferredSize(new java.awt.Dimension(950, 590));

        jPanel8.setBackground(new java.awt.Color(51, 51, 0));
        jPanel8.setLayout(null);

        EnrollStudents1.setBackground(new java.awt.Color(100, 49, 30));
        EnrollStudents1.setOpaque(false);
        EnrollStudents1.setLayout(null);

        ErrorEnroll2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EnrollStudents1.add(ErrorEnroll2);
        ErrorEnroll2.setBounds(180, 250, 510, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Class ID");
        EnrollStudents1.add(jLabel8);
        jLabel8.setBounds(330, 50, 56, 17);
        EnrollStudents1.add(EnrollmentsCid1);
        EnrollmentsCid1.setBounds(410, 50, 175, 30);
        EnrollStudents1.add(EnrollmentsSid2);
        EnrollmentsSid2.setBounds(130, 50, 175, 30);

        jButton4.setText("Drop Class");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        EnrollStudents1.add(jButton4);
        jButton4.setBounds(630, 40, 120, 38);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Student ID");
        EnrollStudents1.add(jLabel9);
        jLabel9.setBounds(40, 50, 90, 17);

        ErrorEnroll3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EnrollStudents1.add(ErrorEnroll3);
        ErrorEnroll3.setBounds(180, 190, 510, 40);

        jTable5.setBackground(new java.awt.Color(204, 204, 204));
        jTable5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable5.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jTable5);

        EnrollStudents1.add(jScrollPane3);
        jScrollPane3.setBounds(40, 132, 720, 280);

        jPanel8.add(EnrollStudents1);
        EnrollStudents1.setBounds(-10, -10, 830, 430);

        UpdatePanel.addTab("Drop Class", jPanel8);

        jPanel7.setBackground(new java.awt.Color(51, 51, 0));
        jPanel7.setLayout(null);

        EnrollStudents.setBackground(new java.awt.Color(51, 51, 0));
        EnrollStudents.setLayout(null);

        ErrorEnroll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EnrollStudents.add(ErrorEnroll);
        ErrorEnroll.setBounds(180, 250, 510, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Class ID");
        EnrollStudents.add(jLabel6);
        jLabel6.setBounds(330, 50, 56, 17);
        EnrollStudents.add(EnrollmentsCid);
        EnrollmentsCid.setBounds(410, 50, 175, 30);
        EnrollStudents.add(EnrollmentsSid1);
        EnrollmentsSid1.setBounds(130, 50, 175, 30);

        jButton3.setText("Enroll Stduent");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        EnrollStudents.add(jButton3);
        jButton3.setBounds(630, 40, 120, 38);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Student ID");
        EnrollStudents.add(jLabel7);
        jLabel7.setBounds(40, 50, 90, 17);

        jTable4.setBackground(new java.awt.Color(204, 204, 204));
        jTable4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable4);

        EnrollStudents.add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 730, 280);

        jPanel7.add(EnrollStudents);
        EnrollStudents.setBounds(0, 0, 820, 430);

        UpdatePanel.addTab("Enroll Student", jPanel7);

        jPanel9.setBackground(new java.awt.Color(51, 51, 0));
        jPanel9.setLayout(null);

        EnrollStudents2.setBackground(new java.awt.Color(140, 49, 0));
        EnrollStudents2.setOpaque(false);
        EnrollStudents2.setLayout(null);

        ErrorEnroll4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EnrollStudents2.add(ErrorEnroll4);
        ErrorEnroll4.setBounds(180, 250, 510, 30);
        EnrollStudents2.add(EnrollmentsSid3);
        EnrollmentsSid3.setBounds(250, 40, 175, 30);

        jButton5.setText("Delete Student");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        EnrollStudents2.add(jButton5);
        jButton5.setBounds(450, 30, 120, 38);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Student ID");
        EnrollStudents2.add(jLabel11);
        jLabel11.setBounds(140, 40, 90, 17);

        ErrorEnroll5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EnrollStudents2.add(ErrorEnroll5);
        ErrorEnroll5.setBounds(180, 190, 510, 40);

        jTable6.setBackground(new java.awt.Color(204, 204, 204));
        jTable6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable6.setGridColor(new java.awt.Color(0, 0, 0));
        jTable6.setOpaque(false);
        jScrollPane4.setViewportView(jTable6);

        EnrollStudents2.add(jScrollPane4);
        jScrollPane4.setBounds(30, 110, 710, 280);

        jPanel9.add(EnrollStudents2);
        EnrollStudents2.setBounds(0, 0, 870, 420);

        UpdatePanel.addTab("Delete a Student", jPanel9);

        UpdatePanel.setBounds(100, 0, 790, 460);
        jLayeredPane3.add(UpdatePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane3);
        jLayeredPane3.setBounds(150, 90, 1000, 520);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(920, 0, 240, 20);

        jLabel16.setBackground(new java.awt.Color(51, 51, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setOpaque(true);
        getContentPane().add(jLabel16);
        jLabel16.setBounds(-10, 0, 1220, 20);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(60, 10));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(160, -40, 20, 640);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 40, 390, 20);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mitesh\\Desktop\\Image.jpg")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(770, 0, 990, 580);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mitesh\\Desktop\\Image.jpg")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(380, 0, 990, 580);

        jLabel3.setBackground(new java.awt.Color(119, 59, 30));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mitesh\\Desktop\\Image.jpg")); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, 0, 1200, 580);

        pack();
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       UpdatePanel.setVisible(false);
        viewpanel.setVisible(true);
       SearchPane.setVisible(false);
       jTable2.setVisible(false);
      java.util.Date t=new java.util.Date();
       jLabel6.setText("\t\t\tWelcome :"+Username);
      
      jLabel10.setText("View Tables");
        showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.students","B#",jTable2);        
        jTable2.setVisible(true);
    }                                        

    private void SearchClassActionPerformed(java.awt.event.ActionEvent evt) {                                            
 
 
        
        String proc="{call mgandhi2.StudentRegSYS.Find_Student(?,?,?)}";
        try
        {
                CallableStatement cb1=con.prepareCall(proc);
                cb1.setString(1,Student_id.getText().toString());
                String errors="";
                cb1.registerOutParameter(2,OracleTypes.VARCHAR);
                cb1.registerOutParameter(3, OracleTypes.CURSOR);
                cb1.execute();

                errors=cb1.getString(2);
        if(errors==null)
        {   
                ResultSet rs=(ResultSet)cb1.getObject(3);
                ConvertToJtable ct=new ConvertToJtable();
                DefaultTableModel model=(DefaultTableModel)jTable1.getModel();    
                model.setRowCount(0);
                jTable1.setModel(model);
                model=ct.ConverttoTable((DefaultTableModel)jTable1.getModel(), rs);    
                jTable1.setModel(model);
              //  JOptionPane.showMessageDialog(null, "Search Successful");
        }
        else
        {
//            Errorclass1.setText("Message : "+errors);
//            Errorclass1.setForeground(Color.red);
              JOptionPane.showMessageDialog(null, "Error:\n "+errors);
        }
        
        
        
        
        
        
        
        
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        
        
        
        
    }                                           

    private void Student_idActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
    }                                          

    private void SearchDetailsActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        
        viewpanel.setVisible(false);
        SearchPane.setVisible(true);
       UpdatePanel.setVisible(false);
        
        jLabel10.setText("Search Data");
        
    }                                             

    private void class_idActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
    }                                        

    private void SearchClass1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        
         String proc="{call mgandhi2.StudentRegSYS.Find_ClassDetails(?,?,?)}";
        try
        {
        CallableStatement cb1=con.prepareCall(proc);
        cb1.setString(1,class_id.getText().toString());
        String errors="";
        cb1.registerOutParameter(2,OracleTypes.VARCHAR);
        cb1.registerOutParameter(3, OracleTypes.CURSOR);
        cb1.execute();
        
        errors=cb1.getString(2);
        if(errors==null)
        {
                ResultSet rs=(ResultSet)cb1.getObject(3);
                ConvertToJtable ct=new ConvertToJtable();
                DefaultTableModel model=(DefaultTableModel)jTable3.getModel();    
                model.setRowCount(0);
                jTable3.setModel(model);
                model=ct.ConverttoTable((DefaultTableModel)jTable3.getModel(), rs);
                jTable3.setModel(model);
//     
          //  JOptionPane.showMessageDialog(null, "Search Successful");
        }
        else
        {
//            Errorclass1.setText("Message : "+errors);
//            Errorclass1.setForeground(Color.red);
              JOptionPane.showMessageDialog(null, "Error:\n "+errors);
        }
        
        
        
        
        
        
        
        
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        
    }                                            

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        
        String Messasge="";
        
        
         String proc="{call mgandhi2.StudentRegSYS.Enroll_Student(?,?,?)}";
        try
        {
        CallableStatement cb1=con.prepareCall(proc);
        cb1.setString(1,EnrollmentsSid1.getText().toString());
        cb1.setString(2,EnrollmentsCid.getText().toString());
       
        cb1.registerOutParameter(3,OracleTypes.VARCHAR);
        cb1.execute();
        
        Messasge=cb1.getString(3);
        System.out.print(Messasge);
        if(Messasge==null)
        {
                    
                       JOptionPane.showMessageDialog(null, "Message : Student "+EnrollmentsSid1.getText()+" is successfully enrolled in class "+EnrollmentsCid.getText());  
                      showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.Enrollments","B#",jTable4);
   
        }
        else if(Messasge.equalsIgnoreCase("You are overloaded"))
        {
                     
             JOptionPane.showMessageDialog(null,Messasge+"\nStudent"+EnrollmentsSid1.getText()+" is successfully enrolled in class "+EnrollmentsCid.getText() );
             showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.Enrollments","B#",jTable4);

            
   
        }
        else
        {
           
              JOptionPane.showMessageDialog(null,"Error message : "+Messasge );

        }
        
        
        
        
        
        
        
        
        }
        catch(Exception ex)
        {
                    
        }
        
        
        
        
        
        
        
        
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        viewpanel.setVisible(false);
        SearchPane.setVisible(false);
        UpdatePanel.setVisible(true);
        jLabel10.setText("Update Data");
        showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.Enrollments","B#",jTable4);
        showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.Enrollments","B#",jTable5);
        showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.Students","B#",jTable6);        

    }                                        

    private void enrollActionPerformed(java.awt.event.ActionEvent evt) {                                       
        jTable2.setVisible(true);
        showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.Enrollments","B#",jTable2);        
    }                                      

    private void logssActionPerformed(java.awt.event.ActionEvent evt) {                                      
        jTable2.setVisible(true);
        showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.logs","logid",jTable2);        
    }                                     

    private void creditsActionPerformed(java.awt.event.ActionEvent evt) {                                        
        jTable2.setVisible(true);
        showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.course_credit","course#",jTable2);        
    }                                       

    private void PrereqActionPerformed(java.awt.event.ActionEvent evt) {                                       
        jTable2.setVisible(true);
        showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.prerequisites","course#",jTable2);        
    }                                      

    private void GradesActionPerformed(java.awt.event.ActionEvent evt) {                                       
        showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.grades","lgrade",jTable2);        
        jTable2.setVisible(true);
    }                                      

    private void CoursesActionPerformed(java.awt.event.ActionEvent evt) {                                        
        jTable2.setVisible(true);
        showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.courses","course#",jTable2);        
    }                                       

    private void ClassesActionPerformed(java.awt.event.ActionEvent evt) {                                        
        
        jTable2.setVisible(true);
        showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.classes","classid",jTable2);
    }                                       

    private void StudentsActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        jTable2.setVisible(true);
        showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.students","B#",jTable2);

    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        
        
          String proc="{call mgandhi2.StudentRegSYS.Drop_Class(?,?,?)}";
        try
        {
        CallableStatement cb1=con.prepareCall(proc);
        cb1.setString(1,EnrollmentsSid2.getText().toString());
        cb1.setString(2,EnrollmentsCid1.getText().toString());
        
       
        cb1.registerOutParameter(3,OracleTypes.VARCHAR);
        
        cb1.execute();
        
        String Errormessage=cb1.getString(3);
        if(Errormessage==null)
        {
               
              JOptionPane.showMessageDialog(null,"Student "+EnrollmentsSid2.getText()+" deleted successfully");
           showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.Enrollments","B#",jTable5);        

        }
        else
        {
            
              JOptionPane.showMessageDialog(null, "Error:\n "+Errormessage);
        }
        
        
        
        
        
        }
        
        
        catch(Exception ex)
        {
          if(ex.toString().contains("integrity"))
                    {
                       JOptionPane.showMessageDialog(null,"integrity constraint (SYSTEM.SYS_C004217) violated - child record found");
                    }
        }
        
        
        
        
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        
        
        
        
           String proc="{call mgandhi2.StudentRegSYS.Delete_Student(?,?)}";
        try
        {
        CallableStatement cb1=con.prepareCall(proc);
        cb1.setString(1,EnrollmentsSid3.getText().toString());
        
       
        cb1.registerOutParameter(2,OracleTypes.VARCHAR);
        
        cb1.execute();
        
        String Errormessage=cb1.getString(2);
        if(Errormessage==null)
        {
               
           showtable("{call mgandhi2.StudentRegSYS.show_details(?,?,?)}", "mgandhi2.students","B#",jTable6);        
              JOptionPane.showMessageDialog(null,"Student "+EnrollmentsSid3.getText()+" deleted successfully");

        }
        else
        {
            
              JOptionPane.showMessageDialog(null, "Error:\n "+Errormessage);
        }
        
        
        
        
        
        }
        
        
        catch(Exception ex)
        {
          if(ex.toString().contains("integrity"))
                    {
                       JOptionPane.showMessageDialog(null,"integrity constraint (SYSTEM.SYS_C004217) violated - child record found");
                    }
        }
        
        
        
        
        
        
        
        

    }                                        

    private void dept_codeActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
    }                                         

    private void SearchClass2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        
        
        
        String Errormessage="";
        
         String proc="{call mgandhi2.StudentRegSYS.Find_Prerequisite_Requirement(?,?,?,?)}";
        try
        {
        CallableStatement cb1=con.prepareCall(proc);
        cb1.setString(1,dept_code.getText().toString());
        cb1.setInt(2,Integer.parseInt(course1.getText().toString()));
       
        cb1.registerOutParameter(3,OracleTypes.VARCHAR);
        cb1.registerOutParameter(4,OracleTypes.CURSOR);
        cb1.execute();
        
        Errormessage=cb1.getString(3);
        if(Errormessage==null)
        {
                ResultSet rs=(ResultSet)cb1.getObject(4);
                ConvertToJtable ct=new ConvertToJtable();
                DefaultTableModel model=(DefaultTableModel)jTable7.getModel();    
                model.setRowCount(0);
                jTable7.setModel(model);
                model=ct.ConverttoTable((DefaultTableModel)jTable7.getModel(), rs);
                jTable7.setModel(model);
                
     
            //JOptionPane.showMessageDialog(null, "Search Successful");
        }
        else
        {
            
              JOptionPane.showMessageDialog(null, "Error:\n "+Errormessage);
        }
        
        
        
        
        
        }
        
        
        catch(Exception ex)
        {
            
        }
        
        
        
        
        
        
    }                                            

    private void course1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        
    }                                       

    
    private void showtable(String procname, String Table_name,String ids, javax.swing.JTable jTable1)
    {
        try{
                    CallableStatement cb=con.prepareCall(procname);
                    cb.setString(1,Table_name);
                    cb.setString(2,ids);
                    cb.registerOutParameter(3, OracleTypes.CURSOR);
                    cb.executeUpdate();
                    ResultSet rs=(ResultSet)cb.getObject(3);
                    ConvertToJtable ct=new ConvertToJtable();
                    DefaultTableModel model=(DefaultTableModel)jTable1.getModel();    
                    model.setRowCount(0);
                    jTable1.setModel(model);
                    model=ct.ConverttoTable((DefaultTableModel)jTable1.getModel(),rs);
                    jTable1.setModel(model);
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                     
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STudentsSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STudentsSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STudentsSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STudentsSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STudentsSystem(con,Username).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton Classes;
    private javax.swing.JScrollPane Classespane;
    private javax.swing.JScrollPane Classespane1;
    private javax.swing.JScrollPane Classespane2;
    private javax.swing.JButton Courses;
    private javax.swing.JPanel EnrollStudents;
    private javax.swing.JPanel EnrollStudents1;
    private javax.swing.JPanel EnrollStudents2;
    private javax.swing.JTextField EnrollmentsCid;
    private javax.swing.JTextField EnrollmentsCid1;
    private javax.swing.JTextField EnrollmentsSid1;
    private javax.swing.JTextField EnrollmentsSid2;
    private javax.swing.JTextField EnrollmentsSid3;
    private javax.swing.JLabel ErrorEnroll;
    private javax.swing.JLabel ErrorEnroll2;
    private javax.swing.JLabel ErrorEnroll3;
    private javax.swing.JLabel ErrorEnroll4;
    private javax.swing.JLabel ErrorEnroll5;
    private javax.swing.JLabel Errorclass;
    private javax.swing.JLabel Errorclass1;
    private javax.swing.JLabel Errorclass2;
    private javax.swing.JButton Grades;
    private javax.swing.JButton Prereq;
    private javax.swing.JButton SearchClass;
    private javax.swing.JButton SearchClass1;
    private javax.swing.JButton SearchClass2;
    private javax.swing.JButton SearchDetails;
    private javax.swing.JTabbedPane SearchPane;
    private javax.swing.JTextField Student_id;
    private javax.swing.JButton Students;
    private javax.swing.JTabbedPane UpdatePanel;
    private javax.swing.JTextField class_id;
    private javax.swing.JTextField course1;
    private javax.swing.JButton credits;
    private javax.swing.JTextField dept_code;
    private javax.swing.JButton enroll;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JButton logss;
    private javax.swing.JPanel viewpanel;
    // End of variables declaration                   
}
